spring:
  profiles:
     active: dev
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    cache: true
    servlet:
      content-type: text/html

server:
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
  ssl:
    key-store: classpath:www.shuobakeji.com.jks
    key-password: 7lBW92V6F8
    key-store-type: JKS
    key-alias: server
http:
  port: 80